### ISSUE TITLE
Please build on 14.04 trusty

### ISSUE THREAD

**Issue by probonopd** [spacemeowx2/switch-lan-play-qt5#1]
https://github.com/spacemeowx2/switch-lan-play-qt5/blob/24dafffc96be914da0dc476567e186db2417fd43/.travis.yml#L10

Please build on 14.04 trusty (which is currently the oldest still-supported distribution), so that the resulting binary can run on all still-supported Ubuntu releases (and other distributions equally old). Thank you.

**Comment by spacemeowx2** [comment]
AppImage could be run on most Linux releases, don't worry about that

**Comment by probonopd** [comment]
if you build on xenial, then the AppImage will not be able to run on trusty.

**Comment by spacemeowx2** [comment]
You can reopen this issue when the first release is out.
